// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzcgvsmxgvutxhqeflzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6Y2d2c214Z3Z1dHhocWVmbHp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMDY0MDMsImV4cCI6MjA3Mzc4MjQwM30.aXnowz7_Iez_LTg5PJsArBkpnSo3xug3NjG-TFTcjCw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});